name: IndexNow

on:
  workflow_run:
    workflows:
      - "pages build and deployment"
    types:
      - completed
  workflow_dispatch:

jobs:
  submit:
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Enviar URLs recentes ao IndexNow
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: "https://miradesconto.github.io/miradesconto/sitemap.xml"
          key: "b72a30284083f4ba3daf46c793b04329"
          key-location: "https://miradesconto.github.io/miradesconto/b72a30284083f4ba3daf46c793b04329.txt"
          endpoint: "api.indexnow.org"
          since: 1
          since-unit: "day"
          lastmod-required: true
          failure-strategy: "error"
